version: '2'
services:
    jhipstersampleoauth2application-mongodb:
        image: mongo:3.6.3
        ports:
            - "27017:27017"
        command: mongos --configdb jhipstersampleoauth2application-mongodb-config
    jhipstersampleoauth2application-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    jhipstersampleoauth2application-mongodb-config:
        image: mongo:3.6.3
        container_name: jhipstersampleoauth2application-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
